function lpfOut = Lowpass(in,Fs,N,PassbandFreq)

filtertype = 'IIR';

lpf = dsp.LowpassFilter('SampleRate',Fs,...
    'FilterType',filtertype,...
    'DesignForMinimumOrder',false,...
    'FilterOrder',N,...
    'PassbandFrequency',PassbandFreq);

lpfOut = lpf(in);
end
